"""generate

Revision ID: 1a95bd207f03
Revises: 
Create Date: 2025-10-21 19:55:28.364462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a95bd207f03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('initial_fill', sa.String(length=255), nullable=False),
    sa.Column('sequence', sa.Text(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('winer', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_statistics_sequence_id'), table_name='statistics')
    op.drop_table('statistics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sequence_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('sequence_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ones_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('zeros_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ones_proportion', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tests_results', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('summary', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('file_reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('statistics_pkey'))
    )
    op.create_index(op.f('ix_statistics_sequence_id'), 'statistics', ['sequence_id'], unique=False)
    op.drop_table('generations')
    # ### end Alembic commands ###
