"""generate

Revision ID: 9b25cc777985
Revises: 
Create Date: 2025-10-21 20:07:23.350357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b25cc777985'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('initial_fill', sa.String(length=255), nullable=False),
    sa.Column('sequence', sa.Text(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('winer', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sequence_id', sa.UUID(), nullable=True),
    sa.Column('sequence_length', sa.Integer(), nullable=True),
    sa.Column('ones_count', sa.Integer(), nullable=True),
    sa.Column('zeros_count', sa.Integer(), nullable=True),
    sa.Column('ones_proportion', sa.Float(), nullable=True),
    sa.Column('tests_results', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('file_reference', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistics_sequence_id'), 'statistics', ['sequence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistics_sequence_id'), table_name='statistics')
    op.drop_table('statistics')
    op.drop_table('generations')
    # ### end Alembic commands ###
